package:
    name: sf_cpp_h5_writer 
    version: 0.0.2

build:
  number: 0

source:
    path: ..

requirements:
    build:
        - make
        - gcc
        - lib_cpp_h5_writer

    run:
        - cppzmq ==4.2.1
        - hdf5 ==1.10.1
        - boost ==1.61.0
        - lib_cpp_h5_writer


about:
    summary: "SwissFEL C++ ZMQ to H5 writer."

